# Generated by Django 3.0.4 on 2020-04-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('ingredient', models.TextField(default='salt')),
                ('recipe', models.TextField(default='None')),
                ('picture', models.ImageField(blank=True, default='default.jpg', upload_to='photos')),
            ],
        ),
    ]
